spring.application.name=sistema-financeiro-api
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/finance}
spring.datasource.username=${DB_USER:finance}
spring.datasource.password=${DB_PASSWORD:finance}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
server.port=8080
